<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>7e88714a-6e8c-4616-8dbd-2861c676aa34</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="8.0.0" />
		<PackageReference Include="Portable.BouncyCastle" Version="1.9.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
		<PackageReference Include="NLog" Version="5.3.4" />
		<PackageReference Include="NLog.Web.AspNetCore" Version="5.3.14" />
		<PackageReference Include="NLog.Extensions.Logging" Version="5.3.14" />
	</ItemGroup>

	<ItemGroup>
		<None Update="nlog.config">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Exceptions\" />
		<Folder Include="wwwroot\" />
	</ItemGroup>

</Project>
